name: "Deploy hugo to GCS"
author: "Filip Chyla"
branding:
  icon: "upload-cloud"
  color: "green"
description: "Deploy a multi-config hugo based website to a Google Cloud Storage bucket"
inputs:
  deployment-target:
    description: "target of hugo deploy command, [[deployment.targets]].name"
    required: true
  deployment-environment:
    description: "build environment, which hugo configuration in config/ to use"
    required: true
  gcp-project-id:
    description: "google cloud project id, used to generate application credentials during runtime"
    required: true
  gcp-service-account-key:
    description: "service account key used for uploading to gcs"
    required: true

runs:
  using: "composite"
  steps:
    # Login to gcloud and export credentials
    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        ppeaceiris/actions-hugoroject_id: ${{ inputs.gcp-project-id }}
        service_account_key: ${{ inputs.gcp-service-account-key }}
        export_default_credentials: true

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "latest"

    - name: Build
      shell: bash
      run: hugo --minify --environment ${{ inputs.deployment-environment }}

    - name: Deploy
      shell: bash
      run: hugo deploy --target="${{ inputs.deployment-target }}" --environment ${{ inputs.deployment-environment }}
